database:
  mysql:
    host: "bjdfuyugmtygaodnbvzy-mysql.services.clever-cloud.com"
    port: "3306"
    username: "ud7odlrnsnhxzgtv"
    password: "HbkGoovOsDvEUiiIYRBu"
    database_name: "bjdfuyugmtygaodnbvzy"
    driver_name: "mysql"
    protocol: "tcp"
    timeout: "5s"

swagger:
  title: "Learning API Docs"
  description: "Learning is application to learning golang."
  version: "1.0"
  host: "go-mysql-api-xapa2c3k2q-as.a.run.app"
  base_path: "/api"
  schemes: ['https']

http_server:
  read_timeout: 10s
  write_timeout: 10s
  read_header_timeout: 10s
