database:
  mysql:
    host: "bjdfuyugmtygaodnbvzy-mysql.services.clever-cloud.com"
    port: "3306"
    username: "ud7odlrnsnhxzgtv"
    password: "HbkGoovOsDvEUiiIYRBu"
    database_name: "bjdfuyugmtygaodnbvzy"
    driver_name: "mysql"
    protocol: "tcp"
    timeout: "5s"

http_server:
  read_timeout: 10s
  write_timeout: 10s
  read_header_timeout: 10s
